language: node_js
node_js:
  - "node"
matrix:
  include:
  - name: "ЗАДАЧА 1"
    env: $TASK=1
  - name: "ЗАДАЧА 2"
    env: $TASK=2
  - name: "ЗАДАЧА 3"
    env: $TASK=3
  - name: "ЗАДАЧА 4"
    env: $TASK=4
  - name: "ЗАДАЧА 5"
    env: $TASK=5
script: "mocha test/smalltest0$TASK.js test/test0$TASK.js"
